[project]
name = "dpvt-experiments"
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[system-requirements]
linux = "4.15"
libc = { family="glibc", version="2.17" }

[dependencies]
python = "*"
biopython = "*"
click = "*"
ete3 = "*"
git-lfs = "*"
historydag = "*"
ipykernel = "*"
lightning = "*"
matplotlib = "*"
notebook = "*"
numpy = "*"
optuna = "*"
pandas = "*"
pytest = "*"
pytorch = "*"
pytorch-lightning = "*"
scikit-learn = "*"
snakemake = "*"
tensorboard = "*"
iqtree = "*"
usher = "*"
tbparse = "*"
seaborn = "*"
papermill = "*"
# R packages
r-base = "*"
r-optparse = "*"
r-remotes = "*"
r-devtools = ">=2.4.5,<3"
r-matrix = ">=1.6_5,<2"

[pypi-dependencies]
dpvt = { path = "../dpvt", editable = true }
dpvtex = { path = ".", editable = true }
