models: ["TraverseNN", "TraverseMaxPooling", "TraverseAvgPooling"]
# models: ["TraverseNN"]
train_data: [
    "FourLeafTrain",
    # "FourLeafFourSiteTrain",
    # "TenLeaf",
    # "ThirtyLeaf",
  ]
test_data: [
    "FourLeafTest",
    # "FourLeafFourSiteTest",
    # "TenLeafTest",
    # "ThirtyLeafTest",
  ]
device: "cpu"
n_optimization_trials: "10"
