models: ["TraverseNN", "TraverseMaxPooling", "TraverseAvgPooling"]
train_data: [
    "FourLeafTrain",
    "FourLeafFourSiteTrain",
    # "TenLeaf",
    # "ThirtyLeaf",
  ]
test_data: [
    "FourLeafTest",
    "FourLeafFourSiteTest",
    # "TenLeafTest",
    # "ThirtyLeafTest",
  ]
device: "cpu"
