models: [
    "TraverseNN",
    "TraverseMaxPooling",
    "TraverseAvgPooling",
    "BaselineReversion", # can only run on CPU!
  ]
train_data: [
  "larch_alisim_alignment_10_seq_100_sites_500_algnmnts_train_spr",
  "larch_alisim_alignment_15_seq_100_sites_500_algnmnts_train_spr",
  "larch_alisim_alignment_20_seq_100_sites_500_algnmnts_train_spr",
  "larch_alisim_alignment_25_seq_100_sites_500_algnmnts_train_spr",
  # "larch_alisim_alignment_50_seq_100_sites_500_algnmnts_train_spr",
  ]
test_data: [
  "larch_alisim_alignment_10_seq_100_sites_200_algnmnts_test",
  "larch_alisim_alignment_15_seq_100_sites_200_algnmnts_test",
  "larch_alisim_alignment_25_seq_100_sites_500_algnmnts_test",
  "larch_alisim_alignment_50_seq_100_sites_500_algnmnts_test",
  # "harrington_subset_1000_alignments_2025_03_17",
  # "harrington_subset_50_alignments_2025_03_20_test_spr",
  "harrington_subset_50_to_100_seqs_50_alignments_2025_03_24_test_spr",
  # "harrington_subset_100_to_150_seqs_50_alignments_2025_03_25_test_spr",
  # "harrington_subset_150_to_200_seqs_50_alignments_2025_03_24_2025-03-26_test_spr",
  ]

device: "cpu"
timestamp: "TODAY"
use_cross_datasets: True
output_dir: "_output"
data_nicknames_path: "my_data_nicknames.json"
evaluate_tree_search: False
use_hyperparameter_optimize: False
n_hyperparameter_trials: 50

hyperparameters:
  learning_rate: [0.0002]
  batch_size: [4]
  accum_grad_batches: [1]
  epochs: [200]
  feature_length: [32]
  dim_mlp_layers: [256]
